/* #define MOTOR_PWM_COUNTER_MAX 300U */
#define VELOCITY_MAX_LIMIT					90.0
#define VELOCITY_ENC_LIMIT 					100
#define MOTOR_PWM_MAX_LIMIT 				7000
#define MOTORA_DEAD_TIME						450			//Left
#define MOTORB_DEAD_TIME						470     //Right

#define VELOCITY_PWM_OUT_MAX				MOTOR_PWM_MAX_LIMIT
#define VELOCITY_PWM_OUT_MIN				-MOTOR_PWM_MAX_LIMIT
#define VELOCITY_INTEGRAL_MAX				15000
#define VELOCITY_INTEGRAL_MIN				-15000
#define DIRECTION_PWM_OUT_MAX				MOTOR_PWM_MAX_LIMIT
#define DIRECTION_PWM_OUT_MIN				-MOTOR_PWM_MAX_LIMIT

/* 电磁导航模式PID参数 */
#define EMN_VELOCITY_P									130.0
#define EMN_VELOCITY_I									EMN_VELOCITY_P/200.0
#define EMN_VELOCITY_D									10.0 //10.0 //50.0
#define EMN_ANGLE_P											300.0
#define EMN_ANGLE_D											10.0
#define EMN_DIRECTION_P									4800 //5500.0
#define EMN_DIRECTION_D									10.0

/* 遥控载重模式PID参数(ReMote Loading) */
#define RML_VELOCITY_P									150.0
#define RML_VELOCITY_I									RML_VELOCITY_P/200.0
#define RML_VELOCITY_D									0.0
#define RML_ANGLE_P											250.0
#define RML_ANGLE_D											6.0
#define RML_DIRECTION_P									100.0
#define RML_DIRECTION_D									16.0

/* 周期定义 unit=ms*/
#define PERIOD_SYSTICK									2   //5			
#define PERIOD_ANGLE_MEASURE						2   //5				
#define PERIOD_ANGLE_CONTROL						2   //5				
#define PERIOD_VELOCITY_MEASURE					10   //10 // 100				
#define PERIOD_VELOCITY_CONTROL					10   //10 // 100
#define PERIOD_DIRECTION_CONTROL				2  //5
#define PERIOD_DIRECTION_MEASURE				2  //5

#define COUNT_ANGLE_MEASURE							(PERIOD_ANGLE_MEASURE / PERIOD_SYSTICK)
#define COUNT_ANGLE_CONTROL							(PERIOD_ANGLE_CONTROL / PERIOD_SYSTICK)
#define COUNT_VELOCITY_MEASURE					(PERIOD_VELOCITY_MEASURE / PERIOD_SYSTICK)
#define COUNT_VELOCITY_CONTROL					(PERIOD_VELOCITY_CONTROL / PERIOD_SYSTICK)
#define COUNT_DIRECTION_CONTROL					(PERIOD_DIRECTION_CONTROL / PERIOD_SYSTICK)
#define COUNT_DIRECTION_MEASURE					(PERIOD_DIRECTION_MEASURE / PERIOD_SYSTICK)
#define COUNT_SYSTICK_MAX								(PERIOD_VELOCITY_CONTROL / PERIOD_SYSTICK)

#define MOTOR_ENCODER_CONSTANT					(260*4)	// 编码器精度
#define MOTOR_VELOCITY_CONSTANT					(1000.0 / (float)PERIOD_VELOCITY_CONTROL / (float)MOTOR_ENCODER_CONSTANT)
	
#define VERTICAL_ANGLE_OFFSET						2
#define DIRECTION_LEFTEDI_OFFSET 				0
#define DIRECTION_RIGHTEDI_OFFSET 			0

#define REMOTE_LOADING_MODE							0U
#define NAVIGATION_MODE									1U
#define REMOTE_RUNNING_MODE							2U
#define NAVIGATION_MODE_CONFIRM					3U

